### PR TITLE
Filter vulnerabilities by "first_found"

### PR DESCRIPTION
**Pull request by jrmcpeek**
The changes in this pull request add the ability to override the default behavior of reporting vulnerabilities based on `last_found` date to instead use `first_found`.

This change allows a workflow where the "Vulnerability Management" project in Jira is initially seeded with all open vulnerabilities. Thereafter, the ingester is run using the `--first-discovery` flag to only create issues identified for the first time in the observation window provided to the run.

This enables the centralization and isolation of the ingestion of vulnerabilities in a "pristine" Jira project prior to moving the tasks/subtasks out to one or more teams to be worked in their normal fashion, in their normal team-based Jira boards, without the integration creating duplicate entries the next time it runs.

In addition, the following miscellaneous changes were made:
- Fixed a `KeyError` exception when Tenable's API returns "None" (literally the string) as the severity value
- Added `tags=tags` to the export vuln check for Jira ticket closure, for tag-filtered runs, to avoid walking through all fixed vulnerabilities when only a subset is interesting to the user
- Updated the README file with the latest printout from `tenable-jira --help`, added an example for tag-based filtering, and added an example usage for the `--first-discovery` flag

Tested working with 3.8.5.

### CODE REVIEW

**Comment by SteveMcGrath** [comment]
using first discovered would mean that VPR updates, temporal updates, CVSS scoring changes, and plugin output changes would not be tracked.

**Comment by jrmcpeek** [comment]
Yeah, understood that the updated values wouldn't occur in this setup.

Currently, the workflow we're using looks like:

1. Full import to VULN project in Jira
2. Split work off to 3 teams for patching/maintenance
3. "First time" imports while the teams are working the items in their backlogs; splitting out new work as it comes in
4. Once the teams have completed the patching work, repeat the process again starting at Step 1, using a "full" import to catch any improperly resolved defects from previous iterations.

This allows us to bring work to whether the teams are, rather than trying to have the tool manage new/in progress/done, or require multiple teams to work out of a single backlog in a "Business" project using Classic Jira.

It's possible that I've misunderstood the intended usage as designed, but this seemed to be fit workflow going to more than one team and thought it might be generally useful to others.

**Comment by SteveMcGrath** [comment]
The process you have defined, while it may work for you just fine for you, falls outside what we generally see folks intending to use the integration towards.  The primary use case is generally to track vuln state and sync it to the issue.  Your workflow discards that entirely for a different design altogether.

Its worth noting that if the intent is to split the work off to different teams, that could be done with multiple runs to different projects using asset tags to break it up.  not sure if it'll work for you, but at least worth mentioning.

This may be considered for inclusion if the behavioral change is made more clear in the documentation.

**Comment by jrmcpeek** [comment]
Happy to beef up the documentation. Which sections are you most concerned about, or would you prefer to see it in a new, broken out section all-together?

I can make those updates, as well as fix the merge conflicts from your 1.1.20 release.

Regarding different runs - these are all for a single product (running in a single AWS VPC), it's just large enough to have multiple scrum teams. Given that, I didn't see trying to split it at the Tenable level made sense - we wanted to keep each logical products assets under a single tag.

**Comment by SteveMcGrath** [comment]
id break out a separate section detailing what this would do, and the potential impact.

as for breaking it out, how are you separating the work between the teams then?

**Comment by jrmcpeek** [comment]
> as for breaking it out, how are you separating the work between the teams then?

Each of the teams are cross-functional, so there's no **technical** distinction on the splitting. It's purely a function of the amount of vulnerabilities that have been identified, relative to other obligations/scope the teams have to work on.

Of course, this tends to get massaged a bit, with a mix of high/medium/low going to each team, cross-cut to vulnerabilities that are simple (run yum/apt) versus deeper engineering work (JDK 1.4 detected: "Why do we have this?" "Well, something needs to run our Java Applets still.").

This workflow may be symptomatic of the fact that this is a legacy product acquisition, with a recent move from data center to cloud - but taking a look at our enterprise Tenable dashboard, we don't appear to the only team that is behind the curve - so I would anticipate that "being behind" is more common than not.

**Comment by jrmcpeek** [comment]
Merge conflict resolved and proposed documentation update included for review.

**Review by SteveMcGrath — APPROVED** [review]

**Pull request merged**
